name: BAWK-E Technologies
favicon: null
layout_spectrum: 0.68515
typography_spectrum: 0.82254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8e908f'
    - '#fdfefe'
    - '#0d141c'
    - '#2e446d'
    - '#b4bfdb'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
